### ISSUE TITLE
ESPHOME update error

### ISSUE THREAD

**Issue by william-sy** [fonske/clack-reader-v3#5]
Not a issue, but a helping hand:

If you get the error trying to update the clack reader on the latest ESPHOME version this already has been resolved!
see this commit: 
https://github.com/fonske/clack-reader-v3/commit/219ebf49e1d7b1fb30b539ed229abe3ce46f6232

If you still have errors about this you will need to do the following: 

```
# Grep this in your ESPHOME directory: 
sudo grep -re lolin_s3 /esphome/config/.esphome/packages/
# You will find something like this:
/esphome/config/.esphome/packages/e29c5466/esphome/board-esp32-wemos-s3.yaml:  board: lolin_s3
/esphome/config/.esphome/packages/bc7d8f18/esphome/board-esp32-wemos-s3.yaml:  board: lolin_s3

# Remove all the directories that match:
sudo rm -rf /esphome/config/.esphome/packages/bc7d8f18
sudo rm -rf /esphome/config/.esphome/packages/e29c5466
```

ESPHOME will now update your clack reader :)

**Comment by kalpik** [comment]
An easier way is to do a "Clean build files" from the three dots menu on the esphome dashboard, and then try another install.

**Comment by kalpik** [comment]
Also, the full PR for this is here: https://github.com/fonske/clack-reader-v3/pull/4/files

**Comment by william-sy** [comment]
> An easier way is to do a "Clean build files" from the three dots menu on the esphome dashboard, and then try another install.

Yes, but this would complain then about the same error so you need to do this before you upgrade esphome else its too late. (at my side of things anyway)

**Comment by kalpik** [comment]
> > An easier way is to do a "Clean build files" from the three dots menu on the esphome dashboard, and then try another install.
> 
> Yes, but this would complain then about the same error so you need to do this before you upgrade esphome else its too late. (at my side of things anyway)

Just checking. Do you have [this](https://github.com/fonske/clack-reader-v3/blob/main/esphome/clack.yaml#L20) in your clack.yaml file? This ensures the correct file is pulled in every time, and then you won't get such errors in the first place. I also discovered it while doing some testing myself. Had created the PR for this here: https://github.com/fonske/clack-reader-v3/pull/3/commits/641ab45bdff1e3137ac1f353008cb2eab6be99d3

**Comment by william-sy** [comment]
Ahh, no I do not!
But now I will thank you very much!

The `clack.yaml` file is not something you update everyday unless there is a huge change / error. 

But this is a good addition to this error/thread indeed that will save some errors!

**Comment by william-sy** [comment]
@fonske  Let's close this issue next week or so. Hopefully that will give people some time to find it, while they try to update to the latest version of esphome

**Comment by kalpik** [comment]
> Ahh, no I do not! But now I will thank you very much!
> 
> The `clack.yaml` file is not something you update everyday unless there is a huge change / error.
> 
> But this is a good addition to this error/thread indeed that will save some errors!

What I do is maintain a "custom" branch in my fork, and in that, I point the clack.yaml to my fork, and the custom branch. That way, it's easy to keep some customizations in your clack.yaml to yourself, while still pulling in all the latest changes from upstream :)

You can see it here: https://github.com/fonske/clack-reader-v3/compare/main...kalpik:clack-reader-v3:custom#diff-82325470434be953eba48f243085de17dd1d8056809f64e84c809a112929b73d

**Comment by william-sy** [comment]
That is neat! will have a look at doing the same :)
