### ISSUE TITLE
Do NOT update to esphome 2023.12.0

### ISSUE THREAD

**Issue by kalpik** [fonske/clack-reader-v3#9]
I updated this morning, and now the board is not connecting to wifi. I'll take it out and try to flash it via USB.

Got a lot of warnings about:

<command-line>: warning: "ARDUINO_USB_CDC_ON_BOOT" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "ARDUINO_USB_CDC_ON_BOOT" redefined
<command-line>: note: this is the location of the previous definition
Compiling .pioenvs/clack/FrameworkArduino/libb64/cencode.c.o

**Comment by kalpik** [comment]
Was able to recover by flashing back 2023.11.6 via USB cable.

**Comment by kalpik** [comment]
esphome 2023.12.2 is safe to flash again. But still get warnings about ARDUINO_USB_CDC_ON_BOOT

**Comment by fonske** [comment]
I have removed the -DARDUINO_USB_CDC_ON_BOOT=0 build flag in board-esp32-wemos-s3.yaml.
No more warnings during compiling so i will close this issue.
